In [1]:
import numpy as np
from tensorflow.keras.layers import Input, Embedding
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
# Generate some random weights
embedding_weights = np.random.rand(10000, 106)
vocabulary_size = 10000

In [3]:
input_layer = Input(shape=(200,), name='text_input')
embedding = Embedding(input_length=200, input_dim=vocabulary_size, output_dim=106, 
                       name='embedding_layer', trainable=False, weights=[embedding_weights])
embedded_text = embedding(input_layer)
embedding_model = Model(inputs=input_layer, outputs=embedded_text)

In [4]:
# Random input sequence of length 200
input_sequence = np.random.randint(0,10000,size=(1,200))
# Extract the embeddings by calling the .predict() method
sequence_embeddings = embedding_model.predict(input_sequence)

In [5]:
from nltk.tokenize import word_tokenize

text = "I had a house and car of my own"
tkns = word_tokenize(text)
tkn_ids = [one_hot(tkn, 200) for tkn in tkns]
input_sequence = pad_sequences([tkn_id for tkn_id in tkn_ids], maxlen=200, dtype="int32", padding="pre", 
                                                               truncating="pre", value=0.0)

# Extract the embeddings by calling the .predict() method
sequence_embeddings = embedding_model.predict(input_sequence)

In [6]:
print(sequence_embeddings)

[[[0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  [0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  [0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  ...
  [0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  [0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  [0.2899627  0.6314077  0.31996    ... 0.8439443  0.9913898  0.76255906]]

 [[0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  [0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  [0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  ...
  [0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  [0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  [0.9925927  0.1990142  0.19136871 ... 0.29245594 0.68264467 0.502004  ]]

 [[0.1039932  0.9681861  0.25049317 ... 0.43206945 0.7814346  0.00642428]
  [0.1039932  0.968186